# Generated by Django 5.1.6 on 2025-04-02 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetinaLabelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('sort_index', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Категория группы признаков описания сетчатки',
                'verbose_name_plural': 'Категория групп признаков описания сетчатки',
                'ordering': ['sort_index'],
            },
        ),
        migrations.CreateModel(
            name='RetinaLabelMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('sort_index', models.IntegerField()),
                ('is_visible', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retina_analysis.retinalabelgroup')),
            ],
            options={
                'verbose_name': 'Метка сетчатки глаза',
                'verbose_name_plural': 'Метки сетчатки глаза',
            },
        ),
    ]
