# Generated by Django 5.1.6 on 2025-04-28 05:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retina_analysis', '0002_retinaimagecroptype_retinafileupload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetinaAnalysisCropTask',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retina_analysis.retinaimagecropoct')),
            ],
            options={
                'verbose_name': 'Задача анализа среза сетчатки',
                'verbose_name_plural': 'Задачи анализа среза сетчатки',
            },
        ),
        migrations.CreateModel(
            name='RetinaAnalysisTask',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Not Started'), (2, 'Processed'), (3, 'Success'), (4, 'Error')], default=1)),
                ('status_update', models.DateTimeField(auto_now=True)),
                ('is_corrected', models.BooleanField(default=False)),
                ('crops', models.ManyToManyField(through='retina_analysis.RetinaAnalysisCropTask', to='retina_analysis.retinaimagecropoct')),
                ('task_detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retina_analysis.retinadetectiontask')),
            ],
            options={
                'verbose_name': 'Задача анализа сетчатки',
                'verbose_name_plural': 'Задачи анализа сетчатки',
            },
        ),
        migrations.AddField(
            model_name='retinaanalysiscroptask',
            name='task_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retina_analysis.retinaanalysistask'),
        ),
    ]
