# Generated by Django 5.1.6 on 2025-04-28 05:57

import django.db.models.deletion
import retina_analysis.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retina_analysis', '0003_retinaanalysiscroptask_retinaanalysistask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetinaAnalysisCorrectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('label_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retina_analysis.retinalabelmark')),
                ('retina_analysis_crop_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retina_analysis.retinaanalysiscroptask')),
            ],
        ),
        migrations.CreateModel(
            name='RetinaAnalysisResult',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Not Started'), (2, 'Processed'), (3, 'Success'), (4, 'Error')], default=1)),
                ('status_update', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=retina_analysis.models.retina_analysis_crop_image_upload)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=retina_analysis.models.retina_analysis_crop_thumbnail_upload)),
                ('score', models.FloatField(blank=True, null=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retina_analysis.retinalabelmark')),
                ('retina_analysis_crop_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retina_analysis.retinaanalysiscroptask')),
            ],
            options={
                'verbose_name': 'Результат анализа среза по метке с изображением',
                'verbose_name_plural': 'Результаты анализа среза по метке с изображением',
            },
        ),
    ]
